/**
 * Contentstack Personalize SDK Integration (v1.0.9+)
 * 
 * This module handles:
 * 1. Analytics tracking - sends user attributes to Contentstack
 * 2. Variant delivery - determines which variants to show based on user attributes
 * 
 * The SDK evaluates user attributes against Personalize experiences and returns
 * variant aliases that can be used with the Delivery SDK to fetch personalized content.
 * 
 * NO HARDCODED VALUES - all variant information comes from the Personalize SDK dynamically.
 * 
 * Uses instance-based approach as per migration guide:
 * https://www.contentstack.com/docs/developers/sdks/personalize-edge-sdk/javascript/javascript-personalize-edge-v109-migration-guide
 */

// SDK instance (not global namespace)
let personalizeInstance: any = null;

// Track initialization state
let isInitialized = false;
let initializationPromise: Promise<any> | null = null;

// Project UID from Contentstack Personalize (this is configuration, not hardcoded mapping)
const PROJECT_UID = process.env.NEXT_PUBLIC_PERSONALIZE_PROJECT_UID || '68a6ec844875734317267dcf';

// ============================================================
// VARIANT ALIAS SUPPORT - ALL DYNAMIC FROM SDK
// ============================================================

/**
 * Variant aliases are auto-generated by Personalize in format:
 * cs_personalize_<experience_short_uid>_<variant_short_uid>
 * 
 * These aliases work DIRECTLY with the Delivery API's x-cs-variant-uid header!
 * No hardcoded mappings needed - the SDK returns the correct aliases based on user attributes.
 */

/**
 * Initialize Personalize SDK (client-side only)
 * Returns the SDK instance for method calls
 * Safe to call multiple times - will only initialize once
 */
export async function initializePersonalize(): Promise<boolean> {
  // Only run on client side
  if (typeof window === 'undefined') {
    console.log('⏭️ Personalize: Skipping initialization (server-side)');
    return false;
  }

  // Already initialized
  if (isInitialized && personalizeInstance) {
    return true;
  }

  // Already initializing
  if (initializationPromise) {
    await initializationPromise;
    return isInitialized;
  }

  // Start initialization
  initializationPromise = (async () => {
    try {
      // Dynamic import to avoid SSR issues
      const PersonalizeModule = await import('@contentstack/personalize-edge-sdk');
      const Personalize = PersonalizeModule.default || PersonalizeModule;
      
      // Initialize and store the SDK INSTANCE (not global namespace)
      personalizeInstance = await Personalize.init(PROJECT_UID);
      isInitialized = true;
      
      return personalizeInstance;
    } catch (error) {
      // Silent fail - don't block the app if personalize fails
      console.warn('Personalize SDK initialization skipped:', error instanceof Error ? error.message : 'Unknown error');
      isInitialized = false;
      return null;
    }
  })();

  await initializationPromise;
  return isInitialized;
}

/**
 * Get the SDK instance (initialize if needed)
 */
async function getSDKInstance(): Promise<any> {
  if (personalizeInstance) {
    return personalizeInstance;
  }
  
  await initializePersonalize();
  return personalizeInstance;
}

/**
 * Set user attributes for Personalize analytics
 * 
 * NOTE: This only sets attributes - it does NOT trigger impressions.
 * Impressions should be triggered when variant content is RENDERED, not when attributes are set.
 * Use triggerImpressionForTeam() in your component's useEffect when variant content is displayed.
 * 
 * @param attributes - User attributes to send
 * @example
 * // In login/auth handler:
 * await setPersonalizeAttributes({
 *   QA_LEVEL: 'HIGH_FLYER',
 *   TEAM_NAME: 'Launch'
 * });
 * 
 * // Then in component where variant content is rendered:
 * useEffect(() => {
 *   if (isHighFlyer) {
 *     triggerImpressionForTeam(teamName);
 *   }
 * }, []);
 */
export async function setPersonalizeAttributes(attributes: {
  QA_LEVEL: string;
  TEAM_NAME: string;
}): Promise<boolean> {
  // Only run on client side
  if (typeof window === 'undefined') {
    return false;
  }

  try {
    // Get SDK instance
    const sdk = await getSDKInstance();
    if (!sdk) {
      return false;
    }
    
    // Use instance method: sdk.set() instead of Personalize.set()
    await sdk.set(attributes);
    console.log(`✅ Personalize: Set attributes - QA_LEVEL: ${attributes.QA_LEVEL}, TEAM_NAME: ${attributes.TEAM_NAME}`);
    
    // NOTE: Do NOT trigger impressions here!
    // According to documentation: "triggerImpression should be called only after 
    // the personalized content is rendered to the user"
    // See: https://www.contentstack.com/docs/personalize/setup-nextjs-website-with-personalize-launch
    
    return true;
    
  } catch (error) {
    console.error('❌ Personalize: Failed to set attributes:', error);
    return false;
  }
}

/**
 * Trigger an impression for analytics
 * 
 * IMPORTANT: Call this ONLY when variant content is actually rendered/displayed to the user!
 * Do NOT call when setting attributes or logging in.
 * 
 * According to Contentstack docs:
 * "We are using useEffect in this example so that the impression is triggered 
 * only on the first render of the component"
 * 
 * @param experienceShortUid - The experience short UID (e.g., '9' for Launch, 'c' for DAM)
 * 
 * @example
 * // In your component where variant content is displayed:
 * useEffect(() => {
 *   triggerImpression('9'); // Launch experience
 * }, []);
 */
export async function triggerImpression(experienceShortUid: string): Promise<boolean> {
  if (typeof window === 'undefined') {
    return false;
  }

  try {
    const sdk = await getSDKInstance();
    if (!sdk) return false;

    await sdk.triggerImpression(experienceShortUid);
    console.log(`✅ Personalize: Triggered impression for experience ${experienceShortUid}`);
    return true;
  } catch (error) {
    console.error(`❌ Personalize: Failed to trigger impression for ${experienceShortUid}:`, error);
    return false;
  }
}

/**
 * Trigger impressions for all active experiences
 * 
 * This function triggers impressions for ALL experiences the user currently matches.
 * Call this when variant content is RENDERED.
 * 
 * NO HARDCODED VALUES - uses SDK's getExperiences() to get active experiences dynamically.
 * 
 * @example
 * // In your component where variant content is displayed:
 * useEffect(() => {
 *   if (userSegment === 'HIGH_FLYER') {
 *     triggerImpressionForActiveExperiences();
 *   }
 * }, []);
 */
export async function triggerImpressionForActiveExperiences(): Promise<boolean> {
  if (typeof window === 'undefined') {
    return false;
  }

  try {
    const experiences = await getExperiences();
    if (!experiences || experiences.length === 0) {
      console.log('📦 Personalize: No active experiences to trigger impressions for');
      return false;
    }

    // Trigger impression for each active experience
    let success = false;
    for (const exp of experiences) {
      if (exp.shortUid) {
        const result = await triggerImpression(exp.shortUid);
        if (result) {
          console.log(`✅ Triggered impression for experience ${exp.shortUid}`);
          success = true;
        }
      }
    }
    return success;
  } catch (error) {
    console.error('❌ Personalize: Failed to trigger impressions:', error);
    return false;
  }
}

// Alias for backwards compatibility
export const triggerImpressionForTeam = triggerImpressionForActiveExperiences;

/**
 * Track a custom event for analytics
 * 
 * Supported events:
 * - click: User clicks on a module
 * - module_complete: User completes a module
 * - quiz_pass: User passes a quiz (score >= 70)
 * - quiz_fail: User fails a quiz (score < 50)
 * - onboarding_complete: User completes onboarding
 * 
 * @param eventName - Name of the event
 * @param eventData - Optional event data
 */
export async function trackEvent(
  eventName: 'click' | 'module_complete' | 'quiz_pass' | 'quiz_fail' | 'onboarding_complete' | string,
  eventData?: Record<string, any>
): Promise<boolean> {
  if (typeof window === 'undefined') {
    return false;
  }

  try {
    const sdk = await getSDKInstance();
    if (!sdk) {
      return false;
    }
    
    // Use instance method: sdk.triggerEvent()
    if (typeof sdk.triggerEvent === 'function') {
      await sdk.triggerEvent(eventName);
      return true;
    }
    
    return false;
  } catch {
    return false;
  }
}

// Alias for backwards compatibility
export const trackPersonalizeEvent = trackEvent;

/**
 * Get active variants for current user
 * Returns an object mapping experience short UIDs to variant short UIDs
 * 
 * @example
 * // Returns: { "9": "a", "c": "b" } where keys are experience IDs, values are variant IDs
 */
export async function getVariants(): Promise<Record<string, string> | null> {
  if (typeof window === 'undefined') {
    return null;
  }

  try {
    const sdk = await getSDKInstance();
    if (!sdk) return null;

    return sdk.getVariants();
  } catch (error) {
    console.error('❌ Personalize: Failed to get variants:', error);
    return null;
  }
}

/**
 * Get active experiences for current user
 * Returns an array of experience objects with shortUid and activeVariantShortUid
 * 
 * @example
 * const experiences = await getExperiences();
 * // Returns: [{shortUid: '9', variantShortUid: '0'}, {shortUid: 'c', variantShortUid: '0'}]
 */
export interface Experience {
  shortUid: string;
  variantShortUid: string;
}

export async function getExperiences(): Promise<Experience[]> {
  if (typeof window === 'undefined') {
    return [];
  }

  try {
    const sdk = await getSDKInstance();
    if (!sdk) return [];

    // getExperiences returns array of {shortUid, activeVariantShortUid}
    const experiences = sdk.getExperiences?.() || [];
    
    // Normalize the response format
    return experiences.map((exp: any) => ({
      shortUid: exp.shortUid || exp.short_uid || '',
      variantShortUid: exp.activeVariantShortUid || exp.variant_short_uid || '0'
    }));
  } catch (error) {
    console.error('❌ Personalize: Failed to get experiences:', error);
    return [];
  }
}

/**
 * Get variant aliases for current user
 * Returns an array of variant alias strings in format: cs_personalize_<exp>_<variant>
 * 
 * These aliases are AUTO-GENERATED by Personalize and work directly with the Delivery API!
 * Pass them to the x-cs-variant-uid header to fetch personalized content.
 * 
 * @example
 * const aliases = await getVariantAliases();
 * // Returns: ["cs_personalize_9_0", "cs_personalize_c_0"]
 * 
 * // Use with Delivery API:
 * fetch(url, { headers: { 'x-cs-variant-uid': aliases.join(',') } })
 */
export async function getVariantAliases(): Promise<string[]> {
  if (typeof window === 'undefined') {
    return [];
  }

  try {
    const sdk = await getSDKInstance();
    if (!sdk) return [];

    // getVariantAliases returns array of alias strings like "cs_personalize_9_0"
    const aliases = sdk.getVariantAliases();
    console.log('📦 Personalize: Retrieved variant aliases:', aliases);
    return aliases || [];
  } catch (error) {
    console.error('❌ Personalize: Failed to get variant aliases:', error);
    return [];
  }
}

/**
 * Get variant alias string formatted for Delivery SDK header
 * Returns a comma-separated string of variant aliases ready to use with Delivery SDK
 * 
 * @example
 * const aliasHeader = await getVariantAliasHeader();
 * // Returns: "launch_high_flyer,dam_rookie" or empty string if no variants
 */
export async function getVariantAliasHeader(): Promise<string> {
  const aliases = await getVariantAliases();
  return aliases.join(',');
}

/**
 * Check if Personalize SDK is ready and has variant information
 */
export async function isPersonalizeReady(): Promise<boolean> {
  if (typeof window === 'undefined') {
    return false;
  }
  
  try {
    const sdk = await getSDKInstance();
    return !!sdk;
  } catch {
    return false;
  }
}

/**
 * Reinitialize the Personalize SDK and get variant aliases
 * 
 * This function:
 * 1. Resets the SDK instance
 * 2. Reinitializes the SDK
 * 3. Waits for SDK to be ready
 * 4. Returns variant aliases
 * 
 * Use this when the first call to getVariantAliases() returns empty
 * and you need to force a refresh.
 */
export async function reinitializeAndGetAliases(): Promise<string[]> {
  if (typeof window === 'undefined') {
    return [];
  }

  try {
    console.log('🔄 Personalize: Reinitializing SDK...');
    
    // Reset state
    personalizeInstance = null;
    isInitialized = false;
    initializationPromise = null;
    
    // Reinitialize
    const success = await initializePersonalize();
    if (!success) {
      console.warn('⚠️ Personalize: Reinit failed');
      return [];
    }
    
    // Wait a bit for SDK to process
    await new Promise(resolve => setTimeout(resolve, 200));
    
    // Get aliases
    const sdk = await getSDKInstance();
    if (!sdk) return [];
    
    const aliases = sdk.getVariantAliases?.() || [];
    console.log('📦 Personalize: Aliases after reinit:', aliases);
    return aliases;
    
  } catch (error) {
    console.error('❌ Personalize: Reinit error:', error);
    return [];
  }
}

// Export for debugging
export function getPersonalizeState() {
  return {
    isInitialized,
    projectUid: PROJECT_UID,
    hasInstance: !!personalizeInstance
  };
}

